
Download_Mirror='https://lax.getlnmp.com'

#default using official link to download, set to n to download files from download mirror set above
#recommend to set it to y
Use_Official='y'

country='US'

Nginx_Modules_Options=''
PHP_Modules_Options=''

# set up default timezone for system, default is UTC
# more choice: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
OS_Timezone='Etc/UTC'
# set up default timezone for PHP, default is UTC
# more choice: https://www.php.net/manual/en/timezones.php
PHP_Timezone='UTC'

# Whether open port 3306 for database remote access in firewall, default is n
Open_DB_Port='n'
##MySQL/MariaDB Data Directory##
MySQL_Data_Dir='/usr/local/mysql/data'
MariaDB_Data_Dir='/usr/local/mariadb/data'
##Default website home directory##
Default_Website_Dir='/home/wwwroot/default'


Enable_Nginx_Lua='n'
Enable_Ngx_FancyIndex='n'
Enable_Swap='y'
Enable_PHP_Exif='n'
Enable_PHP_Fileinfo='y'
Enable_PHP_Ldap='n'
Enable_PHP_Bz2='n'
Enable_PHP_Sodium='y'
Enable_PHP_Imap='n'

# Memory Allocator selected during install: 1=none(default), 2=Jemalloc, 3=TCMalloc
# Set this so MySQL/MariaDB upgrades keep using the same malloc-lib
SelectMalloc=''
